### ISSUE TITLE
Question about the way data is being stored to two tables

### ISSUE THREAD

**Issue by calvinlfer** [thiagoandrade6/cassandra-phantom#18]
I have a question about the way data is being stored [here](https://github.com/thiagoandrade6/cassandra-phantom/blob/master/src/main/scala/com/cassandra/phantom/modeling/database/SongsDatabase.scala#L26)

```scala
def saveOrUpdate(songs: Song): Future[ResultSet] = {
    for {
      _ <- SongsModel.store(songs).future()
      byArtist <- SongsByArtistsModel.store(songs).future
    } yield byArtist
}
```

If the songs model store is okay but songs by artists model fails, won't you end up in an inconsistent state? Wouldn't it be more appropriate to use a logged batch here because if the second persist fails, the rollback will occur to the first table. This way you won't end up in an inconsistent state.

**Comment by thiagoandrade6** [comment]
Yes indeed, at first I didn't want to implement any kind of logic for it, that's why the code is very simple, but you are correct, in a production environment when consistency matters, you should take care of it.

I think it's worth implement the batch update in this case. Would you like to open a PR for it, linking this issue? If not no worries, I can do it later.

Thanks

**Comment by calvinlfer** [comment]
Yeah I can do that!
